



title: my Github Site

url: "http://jmstan.github.io/my-github-repo/"

baseurl: "my-github-repo/"
permalink: pretty
path: /cool/:path/

collections:
	portfolio:
		output: true	
	gallery:
		output: true
	artblog:
		output: true